"""
Pipeline constants and configuration values.
"""

# Segmentation parameters
DEFAULT_WORDS_PER_SECTION = 750
MIN_WORDS_FOR_SPLIT = 1000
SCALE_START_WORDS = 1500
SCALE_END_WORDS = 27000
MIN_SECTIONS = 1
MAX_SECTIONS = 10
CHARS_PER_WORD = 5.0

# Time-based segmentation parameters  
MIN_DURATION_SECONDS = 900  # 15 minutes
SCALE_START_DURATION = 1800  # 30 minutes
SCALE_END_DURATION = 7200  # 2 hours
MERGE_THRESHOLD_RATIO = 0.5

# Processing limits
MAX_CONCURRENT_SECTIONS = 5
MAX_RETRIES = 5
BASE_RETRY_DELAY = 2
MAX_OUTPUT_LENGTH = 30000

# Entity caching
ENTITY_CACHE_COLLECTION = "entity_cache"

# Default model configurations
DEFAULT_TEMPERATURE_ANALYSIS = 0.2
DEFAULT_TEMPERATURE_CREATIVE = 0.4
DEFAULT_TEMPERATURE_FILTERING = 0.1

# Cost calculation constants
LLM_INPUT_TOKEN_COST = 0.0000003
LLM_OUTPUT_TOKEN_COST = 0.0000006
TAVILY_SEARCH_COST = 0.008
ASSEMBLYAI_PER_SECOND_COST = 0.0003