export const FEATURED_VIDEO = [
  {
    id: "M4PzOjM5BJQ",
    url: "https://www.youtube.com/watch?v=M4PzOjM5BJQ&t=1512s&pp=ygUaYWxleCBob3Jtb3ppIG1vZGVybiB3aXNkb20%3D",
    title: "23 Harsh Truths Nobody Wants To Admit - Alex Hormozi (4K)",
    channelName: "Chris Williamson",
    thumbnailUrl: "https://i.ytimg.com/vi/M4PzOjM5BJQ/hqdefault.jpg",
    duration: "PT2H54M29S",
    success: true,
  },
  {
    id: "4FXScrmYKQ0",
    url: "https://www.youtube.com/watch?v=4FXScrmYKQ0&t=513s",
    title: "How To Be So Productive That It Feels ILLEGAL",
    channelName: "Justin Sung",
    thumbnailUrl: "https://i.ytimg.com/vi/4FXScrmYKQ0/hqdefault.jpg",
    duration: "PT32M53S",
    success: true,
  },
  {
    id: "JN3KPFbWCy8",
    url: "https://www.youtube.com/watch?v=JN3KPFbWCy8&pp=0gcJCeAJAYcqIYzv",
    title:
      "Elon Musk: War, AI, Aliens, Politics, Physics, Video Games, and Humanity | Lex Fridman Podcast #400",
    channelName: "Lex Fridman",
    thumbnailUrl: "https://i.ytimg.com/vi/JN3KPFbWCy8/hqdefault.jpg",
    duration: "PT2H16M47S",
    success: true,
  },
  {
    id: "LCEmiRjPEtQ",
    url: "https://www.youtube.com/watch?v=LCEmiRjPEtQ",
    title: "Andrej Karpathy: Software Is Changing (Again)",
    channelName: "Y Combinator",
    thumbnailUrl: "https://i.ytimg.com/vi/LCEmiRjPEtQ/hqdefault.jpg",
    duration: "PT39M32S",
    success: true,
  },
  {
    id: "QmOF0crdyRU",
    url: "https://www.youtube.com/watch?v=QmOF0crdyRU",
    title: "Controlling Your Dopamine For Motivation, Focus & Satisfaction",
    channelName: "Andrew Huberman",
    thumbnailUrl: "https://i.ytimg.com/vi/QmOF0crdyRU/hqdefault.jpg",
    duration: "PT2H16M32S",
    success: true,
  },

  {
    id: "KyfUysrNaco",
    url: "https://www.youtube.com/watch?v=KyfUysrNaco&t=6s&pp=ygUObmF2YWwgcmF2aWthbnQ%3D",
    title: "44 Harsh Truths About The Game Of Life - Naval Ravikant (4K)",
    channelName: "Chris Williamson",
    thumbnailUrl: "https://i.ytimg.com/vi/KyfUysrNaco/hqdefault.jpg",
    duration: "PT3H16M19S",
    success: true,
  },
  {
    id: "RcYjXbSJBN8",
    url: "https://www.youtube.com/watch?v=RcYjXbSJBN8",
    title: "Joe Rogan Experience #1470 - Elon Musk",
    channelName: "PowerfulJRE",
    thumbnailUrl: "https://i.ytimg.com/vi/RcYjXbSJBN8/hqdefault.jpg",
    duration: "PT2H9S",
    success: true,
  },
  {
    id: "NcaQUH2K-wo",
    url: "https://www.youtube.com/watch?v=NcaQUH2K-wo",
    title: "Simon Sinek: The Advice Young People NEED To Hear | E176",
    channelName: "The Diary Of A CEO",
    thumbnailUrl: "https://i.ytimg.com/vi/NcaQUH2K-wo/hqdefault.jpg",
    duration: "PT1H45M4S",
    success: true,
  },
  {
    id: "d7sUWwHugg8",
    url: "https://www.youtube.com/watch?v=d7sUWwHugg8",
    title:
      "Joe Dispenza: You've Been Programmed To Stay BROKE, STUCK & EXHAUSTED - Here's How To Break It!",
    channelName: "Jay Shetty Podcast",
    thumbnailUrl: "https://i.ytimg.com/vi/d7sUWwHugg8/hqdefault.jpg",
    duration: "PT1H13M26S",
    success: true,
  },
  {
    id: "HAnw168huqA",
    url: "https://www.youtube.com/watch?v=HAnw168huqA",
    title: "Think Fast, Talk Smart: Communication Techniques",
    channelName: "Stanford Graduate School of Business",
    thumbnailUrl: "https://i.ytimg.com/vi/HAnw168huqA/hqdefault.jpg",
    duration: "PT58M20S",
    success: true,
  },
  {
    id: "wTBSGgbIvsY",
    url: "https://www.youtube.com/watch?v=wTBSGgbIvsY",
    title:
      "How Meditation Works & Science-Based Effective Meditations | Huberman Lab Podcast #96",
    channelName: "Andrew Huberman",
    thumbnailUrl: "https://i.ytimg.com/vi/wTBSGgbIvsY/hqdefault.jpg",
    duration: "PT2H26M2S",
    success: true,
  },
];
